### PR TITLE
src: add configuration options

### PR DESCRIPTION
**Pull request by mhdawson**
- add configuration options to make it easier to use with
  other projects

Signed-off-by: Michael Dawson <mdawson@devrus.com>

### CODE REVIEW

**Comment by mhdawson** [comment]
I know there was this earlier PR https://github.com/electron/docs-parser/pull/21. Not sure why it stalled out but this is possibly simpler/less of a change. I don't think it would require any changes for the electron usage.

**Comment by mhdawson** [comment]
For context I was exploring what we'd need to be able to using within the Node.js project based on discussion in the next-10 mini summit - https://github.com/nodejs/next-10/pull/102

Also related: https://github.com/nodejs/node/discussions/40953

**Comment by mhdawson** [comment]
It's mostly just externalizing the key things we'd need to change plus the addition or a fileList so that we could incrementally add files to be parsed as we updated the format of the '.md' files.

**Comment by mhdawson** [comment]
With these changes I can run the parser on the Node.js docs tree, with one of the files updated to a version that @bnb had fixed and generated nodejs-api.json with the data for that single API.

**Comment by bnb** [comment]
probably worth noting https://github.com/electron/docs-parser/pull/21 is likely to be preferable to this PR, but this PR seems to be the minimum amount of work needed to make docs-parser usable by Node.js.

**Pull request closed without merging**
